name: Build

on:
  pull_request:
    branches: ["master"]
    types: [closed]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: true
          version: 8.5.1

      - name: Build for production
        run: pnpm run build

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./package.json
  
      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.3.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (andyjjrt|Andy Hung|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
  
      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            # v${{steps.changelog.outputs.version}}
            ${{ steps.changelog.outputs.compareurl }}
            ${{ steps.changelog.outputs.changelog }}